// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./core/components/Counter.vue')['default']
    DashboardLayout: typeof import('./core/components/Layout/DashboardLayout.vue')['default']
    Footer: typeof import('./core/components/Footer.vue')['default']
    HeaderContent: typeof import('./core/components/Layout/HeaderContent.vue')['default']
    LoginForm: typeof import('./core/components/Login/LoginForm.vue')['default']
    Menu: typeof import('./core/components/Navigation/Menu.vue')['default']
    README: typeof import('./core/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./core/components/Navigation/SideBar.vue')['default']
    TopBar: typeof import('./core/components/Navigation/TopBar.vue')['default']
    UsersTable: typeof import('./apps/user/components/UsersTable.vue')['default']
    WButton: typeof import('./core/components/Button/WButton.vue')['default']
    WTable: typeof import('./core/components/Table/WTable.vue')['default']
  }
}

export {}
